"""empty message

Revision ID: 0c48ca3593f6
Revises: 1037adf175a9
Create Date: 2021-09-11 18:35:17.800620

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c48ca3593f6'
down_revision = '1037adf175a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'description',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('orders', 'address',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'address',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('orders', 'description',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
