"""empty message

Revision ID: 3a11b44125c8
Revises: db7d68098249
Create Date: 2021-09-11 23:23:31.371628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a11b44125c8'
down_revision = 'db7d68098249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', mysql.ENUM('CREATED', 'CANCELLED_BY_MERCHANT', 'CANCELLED_BY_ADMIN', 'PROCESSING', 'SHIPPED', 'RECEIVED', 'RETURNED_BY_CUSTOMER', 'RETURNED_BY_ADMIN'), nullable=False))
    # ### end Alembic commands ###
