"""empty message

Revision ID: 3a2ab3a5e876
Revises: 07eb75b40a37
Create Date: 2021-09-15 12:22:34.527537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a2ab3a5e876'
down_revision = '07eb75b40a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('MERCHANT_OWNER', 'MERCHANT_USER', 'ADMIN_SUPER', 'ADMIN_MANAGER', 'ADMIN_USER', name='role'), nullable=False))
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=False))
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', mysql.ENUM('MERCHANT_OWNER', 'MERCHANT_USER', 'ADMIN_SUPER', 'ADMIN_USER'), nullable=False))
    op.drop_column('users', 'email_confirmed')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
