"""empty message

Revision ID: 4099265905e0
Revises: 0c48ca3593f6
Create Date: 2021-09-11 22:44:20.619984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4099265905e0'
down_revision = '0c48ca3593f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('CREATED', 'CANCELLED_BY_MERCHANT', 'CANCELLED_BY_ADMIN', 'PROCESSING', 'SHIPPED', 'RECEIVED', 'RETURNED_BY_CUSTOMER', 'RETURNED_BY_ADMIN', name='orderstatustype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
