"""empty message

Revision ID: 5b04be3f237a
Revises: 0a6024104653
Create Date: 2021-09-17 19:47:43.669333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b04be3f237a'
down_revision = '0a6024104653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'merchant_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'merchant_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'merchant_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'merchant_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
