"""empty message

Revision ID: 6840d603181d
Revises: 5b04be3f237a
Create Date: 2021-09-17 19:50:29.701596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6840d603181d'
down_revision = '5b04be3f237a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchants', 'created_by',
               existing_type=mysql.BIGINT(unsigned=True),
               nullable=True)
    op.alter_column('orders', 'created_by',
               existing_type=mysql.BIGINT(unsigned=True),
               nullable=True)
    op.alter_column('users', 'created_by',
               existing_type=mysql.BIGINT(unsigned=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_by',
               existing_type=mysql.BIGINT(unsigned=True),
               nullable=False)
    op.alter_column('orders', 'created_by',
               existing_type=mysql.BIGINT(unsigned=True),
               nullable=False)
    op.alter_column('merchants', 'created_by',
               existing_type=mysql.BIGINT(unsigned=True),
               nullable=False)
    # ### end Alembic commands ###
