"""empty message

Revision ID: b7af6c9d9f83
Revises: 3a11b44125c8
Create Date: 2021-09-11 23:23:52.203311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7af6c9d9f83'
down_revision = '3a11b44125c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', sa.Enum('UNPAID', 'PAID', name='paymentstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###
