"""empty message

Revision ID: db7d68098249
Revises: 4099265905e0
Create Date: 2021-09-11 23:22:35.523261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7d68098249'
down_revision = '4099265905e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', sa.Enum('CREATED', 'CANCELLED_BY_MERCHANT', 'CANCELLED_BY_ADMIN', 'PROCESSING', 'SHIPPED', 'RECEIVED', 'RETURNED_BY_CUSTOMER', 'RETURNED_BY_ADMIN', name='orderstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###
